// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NukeAuthentication.Scr.Infraestructure;

#nullable disable

namespace NukeAuthentication.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260210224826_InitialCommit")]
    partial class InitialCommit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NukeAuthentication.Scr.Domain.Entitys.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActivedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("actived_by");

                    b.Property<DateTime?>("ActivedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actived_date");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.Property<Guid?>("LastUpdateBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("access_level");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("account_status");

                    b.Property<Guid?>("SuspendedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("suspended_by");

                    b.Property<DateTime?>("SuspendedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_date");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<uint>("Version"));

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("NukeAuthentication.Scr.Domain.Entitys.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean")
                        .HasColumnName("Is_revoked");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_session", (string)null);
                });

            modelBuilder.Entity("NukeAuthentication.Scr.Domain.Entitys.User", b =>
                {
                    b.OwnsOne("NukeAuthentication.Scr.Domain.ValueObjects.Base.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_city");

                            b1.Property<string>("Complement")
                                .HasColumnType("text")
                                .HasColumnName("address_complement");

                            b1.Property<string>("Neighborhood")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_neighborhood");

                            b1.Property<string>("Number")
                                .HasColumnType("text")
                                .HasColumnName("address_number");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_region");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_state");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("address_zip_code");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("NukeAuthentication.Scr.Domain.ValueObjects.Base.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("email_address");

                            b1.Property<string>("Domain")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("email_domain");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("NukeAuthentication.Scr.Domain.ValueObjects.Base.Password", "Password", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("password_hash");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("NukeAuthentication.Scr.Domain.ValueObjects.Base.Phone", "Phone", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("phone_country_code");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(9)
                                .HasColumnType("character varying(9)")
                                .HasColumnName("phone_number");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("NukeAuthentication.Scr.Domain.ValueObjects.Person", "Person", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("BirthDate")
                                .HasColumnType("date")
                                .HasColumnName("birth_date");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.OwnsOne("NukeAuthentication.Scr.Domain.ValueObjects.Base.CPF", "Cpf", b2 =>
                                {
                                    b2.Property<Guid>("PersonUserId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("UnformattedCpf")
                                        .IsRequired()
                                        .HasMaxLength(11)
                                        .HasColumnType("character varying(11)")
                                        .HasColumnName("cpf");

                                    b2.HasKey("PersonUserId");

                                    b2.HasIndex("UnformattedCpf")
                                        .IsUnique();

                                    b2.ToTable("users");

                                    b2.WithOwner()
                                        .HasForeignKey("PersonUserId");
                                });

                            b1.OwnsOne("NukeAuthentication.Scr.Domain.ValueObjects.Base.Name", "Name", b2 =>
                                {
                                    b2.Property<Guid>("PersonUserId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("FirstName")
                                        .IsRequired()
                                        .HasMaxLength(30)
                                        .HasColumnType("character varying(30)")
                                        .HasColumnName("first_name");

                                    b2.Property<string>("LastName")
                                        .IsRequired()
                                        .HasMaxLength(70)
                                        .HasColumnType("character varying(70)")
                                        .HasColumnName("last_name");

                                    b2.HasKey("PersonUserId");

                                    b2.ToTable("users");

                                    b2.WithOwner()
                                        .HasForeignKey("PersonUserId");
                                });

                            b1.Navigation("Cpf")
                                .IsRequired();

                            b1.Navigation("Name")
                                .IsRequired();
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();

                    b.Navigation("Person")
                        .IsRequired();

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("NukeAuthentication.Scr.Domain.Entitys.UserSession", b =>
                {
                    b.HasOne("NukeAuthentication.Scr.Domain.Entitys.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_session_user_id");

                    b.OwnsOne("NukeAuthentication.Scr.Domain.ValueObjects.Base.RefreshToken", "RefreshToken", b1 =>
                        {
                            b1.Property<Guid>("UserSessionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("refresh_token");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("refresh_created_at");

                            b1.Property<DateTime>("ExpiresOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("refresh_expires_on");

                            b1.HasKey("UserSessionId");

                            b1.HasIndex("Code")
                                .IsUnique();

                            b1.ToTable("user_session");

                            b1.WithOwner()
                                .HasForeignKey("UserSessionId");
                        });

                    b.OwnsOne("NukeAuthentication.Scr.Domain.ValueObjects.Base.UserAgentInfo", "UserAgent", b1 =>
                        {
                            b1.Property<Guid>("UserSessionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Browser")
                                .HasColumnType("text")
                                .HasColumnName("browser");

                            b1.Property<string>("BrowserMajor")
                                .HasColumnType("text")
                                .HasColumnName("browser_major");

                            b1.Property<string>("Device")
                                .HasColumnType("text")
                                .HasColumnName("device");

                            b1.Property<string>("DeviceBrand")
                                .HasColumnType("text")
                                .HasColumnName("device_brand");

                            b1.Property<string>("System")
                                .HasColumnType("text")
                                .HasColumnName("system");

                            b1.Property<string>("SystemMajor")
                                .HasColumnType("text")
                                .HasColumnName("system_major");

                            b1.Property<string>("UserAgentComplete")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("user_agent");

                            b1.HasKey("UserSessionId");

                            b1.ToTable("user_session");

                            b1.WithOwner()
                                .HasForeignKey("UserSessionId");
                        });

                    b.Navigation("RefreshToken")
                        .IsRequired();

                    b.Navigation("UserAgent")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
